import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { DropdownToggleButton } from "#/ui/dropdown-toggle-button";

describe("DropdownToggleButton", () => {
  it("passes presentation and accessibility overrides through the prop getter", () => {
    const getToggleButtonProps = vi.fn(
      (props?: Record<string, unknown>) => ({
        ...props,
        "aria-expanded": "true",
        "aria-controls": "menu-id",
      }),
    );

    render(
      <DropdownToggleButton
        disabled
        getToggleButtonProps={getToggleButtonProps}
        className="toggle-class"
        testId="toggle-button"
        ariaLabel="Toggle menu"
      >
        <span data-testid="toggle-icon">icon</span>
      </DropdownToggleButton>,
    );

    expect(getToggleButtonProps).toHaveBeenCalledWith({
      disabled: true,
      className: "toggle-class",
      "data-testid": "toggle-button",
      "aria-label": "Toggle menu",
    });

    const button = screen.getByTestId("toggle-button");
    expect(button).toHaveAttribute("type", "button");
    expect(button).toBeDisabled();
    expect(button).toHaveAttribute("aria-label", "Toggle menu");
    expect(button).toHaveAttribute("aria-expanded", "true");
    expect(button).toHaveAttribute("aria-controls", "menu-id");
    expect(screen.getByTestId("toggle-icon")).toBeInTheDocument();
  });

  it("preserves accessibility attributes generated by Downshift", () => {
    const getToggleButtonProps = vi.fn(
      (props?: Record<string, unknown>) => ({
        ...props,
        "aria-label": "Generated toggle label",
        "aria-expanded": "false",
        "data-testid": "generated-toggle",
      }),
    );

    render(
      <DropdownToggleButton
        disabled={false}
        getToggleButtonProps={getToggleButtonProps}
      >
        icon
      </DropdownToggleButton>,
    );

    expect(getToggleButtonProps).toHaveBeenCalledWith({
      disabled: false,
      className: undefined,
    });
    expect(
      screen.getByRole("button", { name: "Generated toggle label" }),
    ).toHaveAttribute("aria-expanded", "false");
    expect(screen.getByTestId("generated-toggle")).not.toBeDisabled();
  });
});
